apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmGlobals:
  chartHome: "../../helm-charts"

helmCharts:
- name: argocd-app
  valuesInline:
    name: argocd
- name: argocd-app
  valuesInline:
    name: demo
# - name: argocd-app
#   valuesInline:
#     name: prometheus
# - name: argocd-app
#   valuesInline:
#     name: lgtm-distributed
- name: argocd-app
  valuesInline:
    name: dex
- name: argocd-app
  valuesInline:
    name: gateway-system
# - name: argocd-app
#   valuesInline:
#     name: cert-manager
- name: argocd-app
  valuesInline:
    name: external-dns


# - name: intro-to-mltp
#   releaseName: argocd-app
#   valuesInline:
#     name: intro-to-mltp # https://github.com/grafana/intro-to-mltp

