apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: dex
  namespace: dex
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 5556
        portName: http
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: dex
    namespace: dex
