kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: dex
  labels:
    gateway: external-http
spec:
  parentRefs:
  - name: external-http
    namespace: gateway-system
  hostnames:
  - "dex.meatcloud.io"
  rules:
  - backendRefs:
    - name: dex
      port: 5556

