apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-system
resources:
# - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.7.0/standard-install.yaml
- "gateway.yaml"
- certificate-wildcard-meatcloud-io.yaml


# Update the cluster to use the Gateway API:
#  gcloud container clusters update CLUSTER_NAME \
#   --gateway-api=standard \
#   --location=CLUSTER_LOCATION
