# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
# helm repo add argo https://argoproj.github.io/argo-helm
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
- name: argo-cd
  valuesInline:
    crds:
      install: false
  releaseName: argo-cd
  namespace: argocd
  version: 5.46.7 # v2.8.4
  repo: https://argoproj.github.io/argo-helm

resources:
- "https://github.com/argoproj/argo-cd/manifests/crds?ref=v2.8.4"
- "httproute.yaml"

patches:
- path: "./deployment-argo-cd-argocd-server.patch.yaml"
- path: "./argocd-cm.patch.yaml"

