apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../../docker-compose.yml convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mimir
  name: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mimir
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../../docker-compose.yml convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/intro-to-mltp-default: "true"
        io.kompose.service: mimir
    spec:
      containers:
        - args:
            - -ingester.native-histograms-ingestion-enabled=true
            - -config.file=/etc/mimir.yaml
          image: grafana/mimir:2.9.0
          name: mimir
          ports:
            - containerPort: 9009
              hostPort: 9009
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/mimir.yaml
              name: mimir-claim0
      restartPolicy: Always
      volumes:
        - name: mimir-claim0
          persistentVolumeClaim:
            claimName: mimir-claim0
status: {}
