apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../../docker-compose.yml convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tempo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../../docker-compose.yml convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/intro-to-mltp-default: "true"
        io.kompose.service: tempo
    spec:
      containers:
        - args:
            - -config.file=/etc/tempo.yaml
          image: grafana/tempo:2.2.0
          name: tempo
          ports:
            - containerPort: 3200
              hostPort: 3200
              protocol: TCP
            - containerPort: 4317
              hostPort: 4317
              protocol: TCP
            - containerPort: 4318
              hostPort: 4318
              protocol: TCP
            - containerPort: 9411
              hostPort: 9411
              protocol: TCP
            - containerPort: 55680
              hostPort: 55680
              protocol: TCP
            - containerPort: 55681
              hostPort: 55681
              protocol: TCP
            - containerPort: 14250
              hostPort: 14250
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/tempo.yaml
              name: tempo-claim0
      restartPolicy: Always
      volumes:
        - name: tempo-claim0
          persistentVolumeClaim:
            claimName: tempo-claim0
status: {}
