apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lgtm-distributed

helmCharts: 
- name: lgtm-distributed
  namespace: lgtm-distributed
  releaseName: lgtm-distributed
  version: 1.0.0
  repo: https://grafana.github.io/helm-charts